[lldb] Disable UnsafeCurrentTask test on linux (#9503)
This is failing here https://ci.swift.org/job/oss-swift-pr-test-ubuntu-20_04/7767

```
error: no variable named 'currentTask' found in this frame
```

(cherry-picked from commit 63bd9dce09fbc14c6ce2f7de085bdd1a157ce238)